name: node_js
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    name: test & build
    runs-on: ubuntu-bionic
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
      - name: Use Node.js lts/*
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - run: |
          source .travis/before_install.sh
          source .travis/script.sh
          npm ci
